name: Node CI

on:
  push:
    branches: ["master"]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout # 拉取代码
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: build # 下载依赖、打包
        run: |
          npm install
          npm run build

      - name: deploy # 部署到github page
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
        ACCESS_TOKEN: ${{ secrets.REACT_VIRTUAL_LIST_TOKEN }}
        BRANCH: master
        FOLDER: dist
        # REPOSITORY_NAME:
        # TARGET_FOLDER:
